#genome_encoding globals
DEFAULT_RANGE = (-1,1)
WEIGHT_OVERWRITE_MUTATION = 0.05

WEIGHT_MUTATION_COEFFICIENT = 0.2

NOT_MATCHING_GENE_COEFFICIENT = 6
WEIGHT_DIF_COEFFICIENT = 0.2
MAX_DIST = 2 #2

ALL_SPECIES_UNIMPROVED_PURGE = 2

MAX_UNIMPROVED = 8
PARENT_PERCENT = 0.25
MUTATE_NODE_PROB = 0.03
MUTATE_LINK_PROB = 0.05
MUTATE_WEIGHT_PROB = 0.8
MIN_PARENTS = 5
MIN_CHILDREN_BEFORE_TOP_CARRY = 3
BRED_CHILDREN_PRECENT = 0#0.5

MAX_DECIMAL_PRECISION = 4

RECURRENT_CONNECTIONS = False
START_ALL_LINKS = True

#NEAT controller globals
POPULATION_SIZE = 200



#neural_net globals
NUM_TESTS = 1
speedFPS = 30
watchFPS = 5000
FPS = speedFPS



#user globals
BIAS = 1

'''
#flappy globals
FLAP_VALUE = 0.48
PIPEGAPSIZE = 100 #defult 100
'''

#debug globals
iteration = 0
STOP_EVERY = 100
STOP = True
FIT_CHECK = 230
FIT_INC = 1



