#genome_encoding globals
DEFAULT_RANGE = (-1,1)
WEIGHT_OVERWRITE_MUTATION = 0.05
WEIGHT_MUTATION_COEFFICIENT = 0.2
NOT_MATCHING_GENE_COEFFICIENT = 4*4
WEIGHT_DIF_COEFFICIENT = 0.4
MAX_DIST = 3
MAX_UNIMPROVED = 20
TOP_PRECENTAGE = 0.25
MUTATE_NODE_PROB = 0.02
MUTATE_LINK_PROB = 0.05
MUTATE_WEIGHT_PROB = 0.8
MIN_PARENTS = 3

RECURRENT_CONNECTIONS = True
START_ALL_LINKS = False

#NEAT controller globals
POPULATION_SIZE = 60

#neural_net globals
NUM_TESTS = 2
speedFPS = 30
watchFPS = 5000
FPS = speedFPS





'''
#flappy globals
FLAP_VALUE = 0.48
BIAS = 1
PIPEGAPSIZE = 100 #defult 100
'''



